joint1_position_controller:
  type: velocity_controllers/JointPositionController
  # type: velocity_controllers/JointVelocityController
  # type: velocity_controllers/JointEffortController
  joint: joint1
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
  type: velocity_controllers/JointPositionController
  # type: velocity_controllers/JointVelocityController
  # type: velocity_controllers/JointEffortController
  joint: joint2
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
  type: velocity_controllers/JointPositionController
  # type: velocity_controllers/JointVelocityController
  # type: velocity_controllers/JointEffortController
  joint: joint3
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint4_position_controller:
  type: velocity_controllers/JointPositionController
  # type: velocity_controllers/JointVelocityController
  # type: velocity_controllers/JointEffortController
  joint: joint4
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint5_position_controller:
  type: velocity_controllers/JointPositionController
  # type: velocity_controllers/JointVelocityController
  # type: velocity_controllers/JointEffortController
  joint: joint5
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint6_position_controller:
  type: velocity_controllers/JointPositionController
  # type: velocity_controllers/JointVelocityController
  # type: velocity_controllers/JointEffortController
  joint: joint6
  pid: {p: 100.0, i: 0.01, d: 10.0}

  
