controller_list:
  - name: fake_main-arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - left_gripper_joint
      - right_gripper_joint